name: Auto Merge Dependabot

on:
  pull_request_target:
    types: [opened, synchronize, labeled, unlabeled, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v2
    - name: Auto merge
      uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        command: 'merge'
        merge-method: 'squash'
        enable-status-checks: true
        required-status-checks-context: 'build-and-test'
