name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image for JPMC.OrderManagement.DataLoader.Service
      run: docker build -t jpmc-order-management-data-loader:$(date +%s) -f Dockerfile --platform "linux/amd64" --target service --build-arg "mainProject=JPMC.OrderManagement.DataLoader.Service" .

    - uses: actions/checkout@v4
    - name: Build Docker image for JPMC.OrderManagement.API
      run: docker build -t jpmc-order-management-api:$(date +%s) -f Dockerfile --platform "linux/amd64" --target restapi --build-arg "mainProject=JPMC.OrderManagement.API" .
