name: Build, Dockerize, Synth

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-synth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Build Docker images
        run: |
          docker build -t jpmc-order-management-data-loader:$(date +%s) -f Dockerfile --platform "linux/amd64" --target service --build-arg "mainProject=JPMC.OrderManagement.DataLoader.Service" .
          docker build -t jpmc-order-management-api:$(date +%s) -f Dockerfile --platform "linux/amd64" --target restapi --build-arg "mainProject=JPMC.OrderManagement.API" .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '18'
            
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      
      - name: CDK Synth All
        shell: bash
        run: |
          for stack in $(cdk list); do
            echo "Synthesizing stack: $stack"
            cdk synth $stack
            echo "Completed synthesizing $stack"
          done
  
          echo "All stacks have been synthesized."
  